# -*- mode: ruby -*-

platform :macos, '11.0'

target 'CRubyApp' do
  pod 'CRuby', path: '../..'

  target 'CRubyAppTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  each_build_configuration installer do |c|
    {
      ARCHS:                        :arm64,
      VALID_ARCHS:                  :arm64,
      ENABLE_BITCODE:               :NO,
      HEADER_SEARCH_PATHS:          '$SRCROOT/../../../CRuby/include',
      GCC_PREPROCESSOR_DEFINITIONS: '$(inherited) COCOAPODS=1 CRUBY_TEST=1'
    }.each {|k, v| c.build_settings[k.to_s] = v.to_s}
  end

  # Remove library flags from test target xcconfig to avoid duplicate symbols;
  # the test bundle inherits them from the host app via bundle_loader.
  test_xcconfigs = Dir.glob('Pods/Target Support Files/Pods-CRubyAppTests/*.xcconfig')
  test_xcconfigs.each do |path|
    content = File.read(path)
    content.gsub!(/ -l"ruby-static"/, '')
    content.gsub!(/ -l"z"/, '')
    content.gsub!(/ -l"CRuby"/, '')
    File.write(path, content)
  end
end

def each_build_configuration (installer, &block)
  installer.pods_project.build_configurations.each do |config|
    block.call config
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      block.call config
    end
  end
end
