NAME    = 'CRubyApp'
PROJECT = 'project.yml'

BUNDLE_DIR   = 'vendor/bundle'
BUNDLE_TOUCH = "#{BUNDLE_DIR}/.touch"

XCODEPROJ   = "#{NAME}.xcodeproj"
XCWORKSPACE = "#{NAME}.xcworkspace"


def xcodebuild(workspace = XCWORKSPACE)
  "xcodebuild -workspace #{workspace} -scheme #{NAME}"
end


task :default => :test

task :clobber => :clean do
  sh %( rm -rf Pods #{XCODEPROJ} #{XCWORKSPACE} #{BUNDLE_DIR} )
end

task :clean do
  sh %( #{xcodebuild} clean ) if File.exist? XCWORKSPACE
end

task :build => XCWORKSPACE do
  sh %( #{xcodebuild} build )
end

task :test => XCWORKSPACE do
  sh %( #{xcodebuild} test )
end

task :xcode => XCWORKSPACE do
  sh %( open #{XCWORKSPACE} )
end

file BUNDLE_TOUCH do
  sh %( bundle install )
  sh %( touch #{BUNDLE_TOUCH} )
end

file XCWORKSPACE => [XCODEPROJ, BUNDLE_TOUCH] do
  sh %( os=macos noprebuilt=1 bundle exec pod install --verbose )
end

file XCODEPROJ => PROJECT do
  sh %( xcodegen generate )
end
