name: Build

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: xcode
        run: |
          sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
          xcodebuild -version

      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          default:   true
          override:  true

      - name: setup rust targets
        run: |
          rustup target list | grep apple | grep -v '(installed)' | xargs rustup target add

      - name: build
        run: rake build

      - name: check outputs
        run: |
          find CRuby/ -iname '*.a' | xargs ls -lh
          find CRuby/ -iname '*.a' | xargs lipo -info
