name: Release

on:
  push:
    tags: ['v[0-9]*']

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: xcode
        run: xcodebuild -version

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          default:   true
          override:  true

      - name: setup rust targets
        run: |
          rustup target list | grep apple | grep -v '(installed)' | xargs rustup target add

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          rake build
          find CRuby/ -iname '*.a' | xargs ls -lh
          find CRuby/ -iname '*.a' | xargs lipo -info

      - name: create prebuilt archive
        id: archive
        run: |
          rake archive
          find . -iname '*.tar.gz' | xargs ls -lh
          echo path=$(ruby -e 'print Dir.glob("CRuby_prebuilt-*.tar.gz").first') >> $GITHUB_OUTPUT

      - name: create github release
        run: gh release create ${{ github.ref_name }} ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
